name: deploy-to-azure
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch

jobs: 
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - uses: azure/arm-deploy@v1
          with:
            resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP }}
            template: ./ARM-Templates/container-webapp-template.json