name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  issues:
    types: 
      - opened
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps: 
      
      - run: echo "hello step-1"
      - run: echo "hello step-2"

  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    steps: 
    - name: Team 14 Task 4
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'Team 14!'
        color: 'red'