name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps: 
      
      - run: echo "hello step-1"
      - run: echo "hello step-2"
